### ISSUE TITLE
How can we starting training with this repo?

### ISSUE THREAD

**Issue by Adenialzz** [RolandGao/FastImageProcessing#1]
Thank you for sharing your reimplementation. How can we starting training with this repo?

**Comment by RolandGao** [comment]
Currently, this repo has dataset download script, two transformations (pencil drawing and L0 smoothing), and the model definition. I do not have plans to implement the training code right now, so I guess you have to write your own. You can submit a pull request as well after you have successfully implemented it.

**Comment by Adenialzz** [comment]
> Currently, this repo has dataset download script, two transformations (pencil drawing and L0 smoothing), and the model definition. I do not have plans to implement the training code right now, so I guess you have to write your own. You can submit a pull request as well after you have successfully implemented it.

I got it. Thank you for your quick reply.
